/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/material.dart';

class CustomMenuIcons {
  CustomMenuIcons._();

  static const IconData action = Icons.flash_on_outlined;
  static const IconData barchart = Icons.bar_chart_sharp;
  static const IconData dashboard = Icons.dashboard;
  static const IconData notice = Icons.event_note_rounded;
  static const IconData push = Icons.send_outlined;
  static const IconData subline = Icons.remove;
  static const IconData user = Icons.person_pin;
  static const IconData talk = Icons.comment_outlined;
  static const IconData warning = Icons.error_outline;
  static const IconData popup = Icons.filter_none;
  static const IconData campaign = Icons.campaign;
  static const IconData stopWords = Icons.block;
  static const IconData announcement = Icons.announcement;
  static const IconData event = Icons.event_available;
}
